import Head from "next/head";
import { Header } from "../components/Header/Header";
import { Content } from "../components/Content/Content";
import { Footer } from "../components/Footer/Footer";
export default function Home() {
	return (
		<div>
			<Head>
				<title>CliCasa</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<Content/>

			<Footer/>
		</div>
	);
}
